'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'English' | 'Français' | 'العربية' | '中文' | 'Español' | 'हिन्दी';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations for different languages
const translations: Record<Language, Record<string, string>> = {
  'English': {
    // Common
    'create_account': 'Create Account',
    'sign_in': 'Sign In',
    'email': 'Email Address',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'forgot_password': 'Forgot Password?',
    'remember_me': 'Remember me',
    'or_continue_with': 'or continue with',
    'or_sign_in_with': 'or sign in with',
    'or_sign_up_with': 'or sign up with',
    'have_account': 'Already have an account?',
    'no_account': 'Don\'t have an account?',
    'create_account_link': 'Create Account',
    'sign_in_link': 'Sign In',
    'required': 'required',
    'terms_agree': 'I agree to the Terms of Service and Privacy Policy',
    'phone_number': 'Phone Number',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'signing_in': 'Signing In...',
    'creating_account': 'Creating Account...',
    'next_step': 'Next Step',
    'back': 'Back',
    'submit': 'Submit',
    
    // Contact Us page
    'get_in_touch': 'Get In Touch',
    'contact_us': 'Contact Us',
    'contact_subtitle': 'We would love to hear from you. Send us a message and we will get back to you as soon as possible.',
    'first_name_placeholder': 'Enter your first name',
    'last_name_placeholder': 'Enter your last name',
    'email_placeholder': 'Enter your email address',
    'choose_topic': 'Choose a topic',
    'select_one': 'Select one...',
    'general_inquiry': 'General Inquiry',
    'support': 'Support',
    'feedback': 'Feedback',
    'message': 'Message',
    'message_placeholder': 'Type your message...',
    'international_support': 'We offer support in multiple languages and time zones',
    
    // Login page
    'welcome_back': 'Welcome Back',
    'welcome_back_subtitle': 'Sign in to your account to continue',
    'welcome_dc': 'Welcome to Doctor Connect',
    'welcome_dc_subtitle': 'Sign in to access your healthcare dashboard and connect with professionals around the world.',
    'why_choose': 'Why choose Doctor Connect:',
    'benefit_1': 'Access to global healthcare professionals',
    'benefit_2': 'Secure medical record management',
    'benefit_3': 'Easy appointment scheduling',
    'signin_title': 'Sign In',
    'signin_subtitle': 'Welcome back! Please sign in to your account.',
    
    // Register page
    'join_network': 'Join Our Global Healthcare Network',
    'join_subtitle': 'Create your account and connect with healthcare professionals from around the world.',
    'create_title': 'Create Your Account',
    'create_subtitle': 'Let\'s start with some basic information.',
    'security_title': 'Secure Your Account',
    'security_subtitle': 'Create a strong password to protect your account.',
    'account_type_title': 'Choose Account Type',
    'account_type_subtitle': 'Select your role on Doctor Connect.',
    'patient': 'Patient',
    'patient_desc': 'I\'m seeking medical care',
    'doctor': 'Healthcare Provider',
    'doctor_desc': 'I provide medical services',
    'specialty': 'Medical Specialty',
    'license': 'License Number',
    'license_placeholder': 'Enter your medical license number',
    'password_hint': 'Must be at least 6 characters long',
    'confirmation_title': 'You\'re All Set!',
    'confirmation_subtitle': 'Your information has been collected. Click the button below to create your account.',
    'account_summary': 'Account Summary',
    'account_name': 'Name:',
    'account_email': 'Email:',
    'account_type': 'Account Type:',
    'account_specialty': 'Specialty:',
    'multilingual_welcome': 'Bienvenue • 欢迎 • Bienvenido',
    'multilingual_register': '注册 • S\'inscrire • Registrarse',
    'join_thousands': 'Join thousands of patients and doctors worldwide',
  },
  'Français': {
    // Common
    'create_account': 'Créer un compte',
    'sign_in': 'Se connecter',
    'email': 'Adresse e-mail',
    'password': 'Mot de passe',
    'confirm_password': 'Confirmer le mot de passe',
    'forgot_password': 'Mot de passe oublié?',
    'remember_me': 'Se souvenir de moi',
    'or_continue_with': 'ou continuer avec',
    'or_sign_in_with': 'ou se connecter avec',
    'or_sign_up_with': 'ou s\'inscrire avec',
    'have_account': 'Vous avez déjà un compte?',
    'no_account': 'Vous n\'avez pas de compte?',
    'create_account_link': 'Créer un compte',
    'sign_in_link': 'Se connecter',
    'required': 'requis',
    'terms_agree': 'J\'accepte les Conditions d\'utilisation et la Politique de confidentialité',
    'phone_number': 'Numéro de téléphone',
    'first_name': 'Prénom',
    'last_name': 'Nom',
    'signing_in': 'Connexion en cours...',
    'creating_account': 'Création du compte...',
    'next_step': 'Étape suivante',
    'back': 'Retour',
    'submit': 'Soumettre',
    
    // Contact Us page
    'get_in_touch': 'Contactez-nous',
    'contact_us': 'Nous Contacter',
    'contact_subtitle': 'Nous serions ravis d\'avoir de vos nouvelles. Envoyez-nous un message et nous vous répondrons dès que possible.',
    'first_name_placeholder': 'Entrez votre prénom',
    'last_name_placeholder': 'Entrez votre nom',
    'email_placeholder': 'Entrez votre adresse e-mail',
    'choose_topic': 'Choisissez un sujet',
    'select_one': 'Sélectionnez...',
    'general_inquiry': 'Demande générale',
    'support': 'Support',
    'feedback': 'Commentaires',
    'message': 'Message',
    'message_placeholder': 'Tapez votre message...',
    'international_support': 'Nous offrons une assistance en plusieurs langues et fuseaux horaires',
    
    // Login page
    'welcome_back': 'Bon retour',
    'welcome_back_subtitle': 'Connectez-vous à votre compte pour continuer',
    'welcome_dc': 'Bienvenue à Doctor Connect',
    'welcome_dc_subtitle': 'Connectez-vous pour accéder à votre tableau de bord de santé et communiquer avec des professionnels du monde entier.',
    'why_choose': 'Pourquoi choisir Doctor Connect:',
    'benefit_1': 'Accès aux professionnels de santé du monde entier',
    'benefit_2': 'Gestion sécurisée des dossiers médicaux',
    'benefit_3': 'Prise de rendez-vous facile',
    'signin_title': 'Connexion',
    'signin_subtitle': 'Bon retour! Veuillez vous connecter à votre compte.',
    
    // Register page
    'join_network': 'Rejoignez notre réseau mondial de soins de santé',
    'join_subtitle': 'Créez votre compte et connectez-vous avec des professionnels de santé du monde entier.',
    'create_title': 'Créez votre compte',
    'create_subtitle': 'Commençons par quelques informations de base.',
    'security_title': 'Sécurisez votre compte',
    'security_subtitle': 'Créez un mot de passe fort pour protéger votre compte.',
    'account_type_title': 'Choisissez le type de compte',
    'account_type_subtitle': 'Sélectionnez votre rôle sur Doctor Connect.',
    'patient': 'Patient',
    'patient_desc': 'Je cherche des soins médicaux',
    'doctor': 'Professionnel de santé',
    'doctor_desc': 'Je fournis des services médicaux',
    'specialty': 'Spécialité médicale',
    'license': 'Numéro de licence',
    'license_placeholder': 'Entrez votre numéro de licence médicale',
    'password_hint': 'Doit comporter au moins 6 caractères',
    'confirmation_title': 'Tout est prêt!',
    'confirmation_subtitle': 'Vos informations ont été collectées. Cliquez sur le bouton ci-dessous pour créer votre compte.',
    'account_summary': 'Résumé du compte',
    'account_name': 'Nom:',
    'account_email': 'Email:',
    'account_type': 'Type de compte:',
    'account_specialty': 'Spécialité:',
    'multilingual_welcome': 'Welcome • 欢迎 • Bienvenido',
    'multilingual_register': '注册 • Register • Registrarse',
    'join_thousands': 'Rejoignez des milliers de patients et de médecins du monde entier',
  },
  'العربية': {
    // Common
    'create_account': 'إنشاء حساب',
    'sign_in': 'تسجيل الدخول',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'confirm_password': 'تأكيد كلمة المرور',
    'forgot_password': 'نسيت كلمة المرور؟',
    'remember_me': 'تذكرني',
    'or_continue_with': 'أو المتابعة باستخدام',
    'or_sign_in_with': 'أو تسجيل الدخول باستخدام',
    'or_sign_up_with': 'أو التسجيل باستخدام',
    'have_account': 'هل لديك حساب بالفعل؟',
    'no_account': 'ليس لديك حساب؟',
    'create_account_link': 'إنشاء حساب',
    'sign_in_link': 'تسجيل الدخول',
    'required': 'مطلوب',
    'terms_agree': 'أوافق على شروط الخدمة وسياسة الخصوصية',
    'phone_number': 'رقم الهاتف',
    'first_name': 'الاسم الأول',
    'last_name': 'اسم العائلة',
    'signing_in': 'جاري تسجيل الدخول...',
    'creating_account': 'جاري إنشاء الحساب...',
    'next_step': 'الخطوة التالية',
    'back': 'رجوع',
    'submit': 'إرسال',
    
    // Contact Us page
    'get_in_touch': 'تواصل معنا',
    'contact_us': 'اتصل بنا',
    'contact_subtitle': 'يسعدنا سماع رأيك. أرسل لنا رسالة وسنرد عليك في أقرب وقت ممكن.',
    'first_name_placeholder': 'أدخل اسمك الأول',
    'last_name_placeholder': 'أدخل اسم العائلة',
    'email_placeholder': 'أدخل عنوان بريدك الإلكتروني',
    'choose_topic': 'اختر موضوعًا',
    'select_one': 'اختر واحدًا...',
    'general_inquiry': 'استفسار عام',
    'support': 'الدعم',
    'feedback': 'الملاحظات',
    'message': 'الرسالة',
    'message_placeholder': 'اكتب رسالتك...',
    'international_support': 'نقدم الدعم بعدة لغات ومناطق زمنية',
    
    // Login page
    'welcome_back': 'مرحبًا بعودتك',
    'welcome_back_subtitle': 'قم بتسجيل الدخول إلى حسابك للمتابعة',
    'welcome_dc': 'مرحبًا بكم في دكتور كونيكت',
    'welcome_dc_subtitle': 'قم بتسجيل الدخول للوصول إلى لوحة معلومات الرعاية الصحية والتواصل مع المتخصصين حول العالم.',
    'why_choose': 'لماذا تختار دكتور كونيكت:',
    'benefit_1': 'الوصول إلى متخصصي الرعاية الصحية العالميين',
    'benefit_2': 'إدارة آمنة للسجلات الطبية',
    'benefit_3': 'تحديد المواعيد بسهولة',
    'signin_title': 'تسجيل الدخول',
    'signin_subtitle': 'مرحبًا بعودتك! يرجى تسجيل الدخول إلى حسابك.',
    
    // Register page
    'join_network': 'انضم إلى شبكتنا العالمية للرعاية الصحية',
    'join_subtitle': 'أنشئ حسابك وتواصل مع متخصصي الرعاية الصحية من جميع أنحاء العالم.',
    'create_title': 'إنشاء حسابك',
    'create_subtitle': 'دعنا نبدأ ببعض المعلومات الأساسية.',
    'security_title': 'تأمين حسابك',
    'security_subtitle': 'قم بإنشاء كلمة مرور قوية لحماية حسابك.',
    'account_type_title': 'اختر نوع الحساب',
    'account_type_subtitle': 'حدد دورك في دكتور كونيكت.',
    'patient': 'مريض',
    'patient_desc': 'أبحث عن رعاية طبية',
    'doctor': 'مقدم رعاية صحية',
    'doctor_desc': 'أقدم خدمات طبية',
    'specialty': 'التخصص الطبي',
    'license': 'رقم الترخيص',
    'license_placeholder': 'أدخل رقم ترخيصك الطبي',
    'password_hint': 'يجب أن تكون على الأقل 6 أحرف',
    'confirmation_title': 'كل شيء جاهز!',
    'confirmation_subtitle': 'تم جمع معلوماتك. انقر على الزر أدناه لإنشاء حسابك.',
    'account_summary': 'ملخص الحساب',
    'account_name': 'الاسم:',
    'account_email': 'البريد الإلكتروني:',
    'account_type': 'نوع الحساب:',
    'account_specialty': 'التخصص:',
    'multilingual_welcome': 'Welcome • Bienvenue • Bienvenido',
    'multilingual_register': 'Register • S\'inscrire • Registrarse',
    'join_thousands': 'انضم إلى آلاف المرضى والأطباء من جميع أنحاء العالم',
  },
  '中文': {
    // Common
    'create_account': '创建账户',
    'sign_in': '登录',
    'email': '电子邮件地址',
    'password': '密码',
    'confirm_password': '确认密码',
    'forgot_password': '忘记密码？',
    'remember_me': '记住我',
    'or_continue_with': '或继续使用',
    'or_sign_in_with': '或使用以下方式登录',
    'or_sign_up_with': '或使用以下方式注册',
    'have_account': '已有账户？',
    'no_account': '没有账户？',
    'create_account_link': '创建账户',
    'sign_in_link': '登录',
    'required': '必填',
    'terms_agree': '我同意服务条款和隐私政策',
    'phone_number': '电话号码',
    'first_name': '名字',
    'last_name': '姓氏',
    'signing_in': '登录中...',
    'creating_account': '创建账户中...',
    'next_step': '下一步',
    'back': '返回',
    'submit': '提交',
    
    // Contact Us page
    'get_in_touch': '联系我们',
    'contact_us': '联系我们',
    'contact_subtitle': '我们很乐意听到您的声音。发送消息给我们，我们会尽快回复您。',
    'first_name_placeholder': '输入您的名字',
    'last_name_placeholder': '输入您的姓氏',
    'email_placeholder': '输入您的电子邮件地址',
    'choose_topic': '选择主题',
    'select_one': '选择一个...',
    'general_inquiry': '一般咨询',
    'support': '支持服务',
    'feedback': '反馈意见',
    'message': '消息',
    'message_placeholder': '输入您的消息...',
    'international_support': '我们提供多种语言和时区的支持',
    
    // Login page
    'welcome_back': '欢迎回来',
    'welcome_back_subtitle': '登录您的账户以继续',
    'welcome_dc': '欢迎来到医生连接',
    'welcome_dc_subtitle': '登录以访问您的医疗保健仪表板并与世界各地的专业人士联系。',
    'why_choose': '为什么选择医生连接：',
    'benefit_1': '访问全球医疗保健专业人士',
    'benefit_2': '安全的医疗记录管理',
    'benefit_3': '轻松预约安排',
    'signin_title': '登录',
    'signin_subtitle': '欢迎回来！请登录您的账户。',
    
    // Register page
    'join_network': '加入我们的全球医疗保健网络',
    'join_subtitle': '创建您的账户并与来自世界各地的医疗保健专业人士联系。',
    'create_title': '创建您的账户',
    'create_subtitle': '让我们从一些基本信息开始。',
    'security_title': '保护您的账户',
    'security_subtitle': '创建一个强密码来保护您的账户。',
    'account_type_title': '选择账户类型',
    'account_type_subtitle': '选择您在医生连接的角色。',
    'patient': '患者',
    'patient_desc': '我正在寻求医疗护理',
    'doctor': '医疗保健提供者',
    'doctor_desc': '我提供医疗服务',
    'specialty': '医疗专业',
    'license': '执照号码',
    'license_placeholder': '输入您的医疗执照号码',
    'password_hint': '必须至少包含6个字符',
    'confirmation_title': '一切就绪！',
    'confirmation_subtitle': '您的信息已收集完毕。点击下面的按钮创建您的账户。',
    'account_summary': '账户摘要',
    'account_name': '姓名：',
    'account_email': '电子邮件：',
    'account_type': '账户类型：',
    'account_specialty': '专业：',
    'multilingual_welcome': 'Welcome • Bienvenue • Bienvenido',
    'multilingual_register': 'Register • S\'inscrire • Registrarse',
    'join_thousands': '加入来自世界各地的数千名患者和医生',
  },
  'Español': {
    // Common
    'create_account': 'Crear Cuenta',
    'sign_in': 'Iniciar Sesión',
    'email': 'Dirección de Correo',
    'password': 'Contraseña',
    'confirm_password': 'Confirmar Contraseña',
    'forgot_password': '¿Olvidó su contraseña?',
    'remember_me': 'Recuérdame',
    'or_continue_with': 'o continuar con',
    'or_sign_in_with': 'o iniciar sesión con',
    'or_sign_up_with': 'o registrarse con',
    'have_account': '¿Ya tiene una cuenta?',
    'no_account': '¿No tiene una cuenta?',
    'create_account_link': 'Crear Cuenta',
    'sign_in_link': 'Iniciar Sesión',
    'required': 'requerido',
    'terms_agree': 'Acepto los Términos de Servicio y la Política de Privacidad',
    'phone_number': 'Número de Teléfono',
    'first_name': 'Nombre',
    'last_name': 'Apellido',
    'signing_in': 'Iniciando sesión...',
    'creating_account': 'Creando cuenta...',
    'next_step': 'Siguiente Paso',
    'back': 'Atrás',
    'submit': 'Enviar',
    
    // Contact Us page
    'get_in_touch': 'Ponte en Contacto',
    'contact_us': 'Contáctanos',
    'contact_subtitle': 'Nos encantaría saber de ti. Envíanos un mensaje y te responderemos lo antes posible.',
    'first_name_placeholder': 'Introduce tu nombre',
    'last_name_placeholder': 'Introduce tus apellidos',
    'email_placeholder': 'Introduce tu correo electrónico',
    'choose_topic': 'Elige un tema',
    'select_one': 'Selecciona uno...',
    'general_inquiry': 'Consulta general',
    'support': 'Soporte',
    'feedback': 'Comentarios',
    'message': 'Mensaje',
    'message_placeholder': 'Escribe tu mensaje...',
    'international_support': 'Ofrecemos soporte en múltiples idiomas y zonas horarias',
    
    // Login page
    'welcome_back': 'Bienvenido de Nuevo',
    'welcome_back_subtitle': 'Inicie sesión en su cuenta para continuar',
    'welcome_dc': 'Bienvenido a Doctor Connect',
    'welcome_dc_subtitle': 'Inicie sesión para acceder a su panel de salud y conectarse con profesionales de todo el mundo.',
    'why_choose': '¿Por qué elegir Doctor Connect?:',
    'benefit_1': 'Acceso a profesionales de la salud globales',
    'benefit_2': 'Gestión segura de registros médicos',
    'benefit_3': 'Programación fácil de citas',
    'signin_title': 'Iniciar Sesión',
    'signin_subtitle': '¡Bienvenido de nuevo! Por favor inicie sesión en su cuenta.',
    
    // Register page
    'join_network': 'Únase a Nuestra Red Global de Salud',
    'join_subtitle': 'Cree su cuenta y conéctese con profesionales de la salud de todo el mundo.',
    'create_title': 'Cree Su Cuenta',
    'create_subtitle': 'Comencemos con información básica.',
    'security_title': 'Asegure Su Cuenta',
    'security_subtitle': 'Cree una contraseña segura para proteger su cuenta.',
    'account_type_title': 'Elija el Tipo de Cuenta',
    'account_type_subtitle': 'Seleccione su rol en Doctor Connect.',
    'patient': 'Paciente',
    'patient_desc': 'Busco atención médica',
    'doctor': 'Proveedor de Salud',
    'doctor_desc': 'Proporciono servicios médicos',
    'specialty': 'Especialidad Médica',
    'license': 'Número de Licencia',
    'license_placeholder': 'Ingrese su número de licencia médica',
    'password_hint': 'Debe tener al menos 6 caracteres',
    'confirmation_title': '¡Todo Listo!',
    'confirmation_subtitle': 'Su información ha sido recopilada. Haga clic en el botón a continuación para crear su cuenta.',
    'account_summary': 'Resumen de la Cuenta',
    'account_name': 'Nombre:',
    'account_email': 'Correo:',
    'account_type': 'Tipo de Cuenta:',
    'account_specialty': 'Especialidad:',
    'multilingual_welcome': 'Welcome • Bienvenue • 欢迎',
    'multilingual_register': 'Register • S\'inscrire • 注册',
    'join_thousands': 'Únase a miles de pacientes y médicos de todo el mundo',
  },
  'हिन्दी': {
    // Common
    'create_account': 'खाता बनाएं',
    'sign_in': 'साइन इन करें',
    'email': 'ईमेल पता',
    'password': 'पासवर्ड',
    'confirm_password': 'पासवर्ड की पुष्टि करें',
    'forgot_password': 'पासवर्ड भूल गए?',
    'remember_me': 'मुझे याद रखें',
    'or_continue_with': 'या इसके साथ जारी रखें',
    'or_sign_in_with': 'या इसके साथ साइन इन करें',
    'or_sign_up_with': 'या इसके साथ साइन अप करें',
    'have_account': 'पहले से खाता है?',
    'no_account': 'खाता नहीं है?',
    'create_account_link': 'खाता बनाएं',
    'sign_in_link': 'साइन इन करें',
    'required': 'आवश्यक',
    'terms_agree': 'मैं सेवा की शर्तों और गोपनीयता नीति से सहमत हूं',
    'phone_number': 'फोन नंबर',
    'first_name': 'पहला नाम',
    'last_name': 'अंतिम नाम',
    'signing_in': 'साइन इन हो रहा है...',
    'creating_account': 'खाता बन रहा है...',
    'next_step': 'अगला कदम',
    'back': 'वापस',
    'submit': 'जमा करें',
    
    // Contact Us page
    'get_in_touch': 'संपर्क करें',
    'contact_us': 'हमसे संपर्क करें',
    'contact_subtitle': 'हमें आपसे सुनना अच्छा लगेगा। हमें एक संदेश भेजें और हम जल्द से जल्द आपसे संपर्क करेंगे।',
    'first_name_placeholder': 'अपना पहला नाम दर्ज करें',
    'last_name_placeholder': 'अपना अंतिम नाम दर्ज करें',
    'email_placeholder': 'अपना ईमेल पता दर्ज करें',
    'choose_topic': 'विषय चुनें',
    'select_one': 'एक चुनें...',
    'general_inquiry': 'सामान्य पूछताछ',
    'support': 'सहायता',
    'feedback': 'प्रतिक्रिया',
    'message': 'संदेश',
    'message_placeholder': 'अपना संदेश टाइप करें...',
    'international_support': 'हम कई भाषाओं और समय क्षेत्रों में सहायता प्रदान करते हैं',
    
    // Login page
    'welcome_back': 'वापसी पर स्वागत है',
    'welcome_back_subtitle': 'जारी रखने के लिए अपने खाते में साइन इन करें',
    'welcome_dc': 'डॉक्टर कनेक्ट में आपका स्वागत है',
    'welcome_dc_subtitle': 'अपने स्वास्थ्य डैशबोर्ड तक पहुंचने और दुनिया भर के पेशेवरों से जुड़ने के लिए साइन इन करें।',
    'why_choose': 'डॉक्टर कनेक्ट क्यों चुनें:',
    'benefit_1': 'वैश्विक स्वास्थ्य पेशेवरों तक पहुंच',
    'benefit_2': 'सुरक्षित चिकित्सा रिकॉर्ड प्रबंधन',
    'benefit_3': 'आसान अपॉइंटमेंट शेड्यूलिंग',
    'signin_title': 'साइन इन करें',
    'signin_subtitle': 'वापसी पर स्वागत है! कृपया अपने खाते में साइन इन करें।',
    
    // Register page
    'join_network': 'हमारे वैश्विक स्वास्थ्य देखभाल नेटवर्क से जुड़ें',
    'join_subtitle': 'अपना खाता बनाएं और दुनिया भर के स्वास्थ्य पेशेवरों से जुड़ें।',
    'create_title': 'अपना खाता बनाएं',
    'create_subtitle': 'कुछ बुनियादी जानकारी से शुरू करते हैं।',
    'security_title': 'अपने खाते को सुरक्षित करें',
    'security_subtitle': 'अपने खाते को सुरक्षित करने के लिए एक मजबूत पासवर्ड बनाएं।',
    'account_type_title': 'खाता प्रकार चुनें',
    'account_type_subtitle': 'डॉक्टर कनेक्ट पर अपनी भूमिका का चयन करें।',
    'patient': 'रोगी',
    'patient_desc': 'मुझे चिकित्सा देखभाल की तलाश है',
    'doctor': 'स्वास्थ्य सेवा प्रदाता',
    'doctor_desc': 'मैं चिकित्सा सेवाएं प्रदान करता हूं',
    'specialty': 'चिकित्सा विशेषज्ञता',
    'license': 'लाइसेंस नंबर',
    'license_placeholder': 'अपना चिकित्सा लाइसेंस नंबर दर्ज करें',
    'password_hint': 'कम से कम 6 अक्षर होने चाहिए',
    'confirmation_title': 'आप तैयार हैं!',
    'confirmation_subtitle': 'आपकी जानकारी एकत्र कर ली गई है। अपना खाता बनाने के लिए नीचे दिए गए बटन पर क्लिक करें।',
    'account_summary': 'खाता सारांश',
    'account_name': 'नाम:',
    'account_email': 'ईमेल:',
    'account_type': 'खाता प्रकार:',
    'account_specialty': 'विशेषज्ञता:',
    'multilingual_welcome': 'Welcome • Bienvenue • Bienvenido',
    'multilingual_register': 'Register • S\'inscrire • Registrarse',
    'join_thousands': 'दुनिया भर के हजारों रोगियों और डॉक्टरों से जुड़ें',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('English');

  // Load language from localStorage on initial render
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 